### ISSUE TITLE
Extension Kdyby\Translation\DI\TranslationExtension not found

### ISSUE THREAD

**Issue by buttasam** [sousedskapomoc/sousedskapomoc_cz#37]
Hi,
after installation `composer install` and running application (PHP 7.4.3, MacOS), I got this error:
<img width="1221" alt="missing_kdyby_extension" src="https://user-images.githubusercontent.com/6898290/76793209-f29f5280-67c4-11ea-82ce-07b44c74fb97.png">

This extension should be probably present in `composer.json`. I fixed it localy: `composer require kdyby/translation`

It this correct?

**Comment by cermakpavel** [comment]
@buttasam Thank for your report. It should be fixed now.
