### ISSUE TITLE
Introdude CD/CI into project

### ISSUE THREAD

**Issue by hunaczech** [sousedskapomoc/sousedskapomoc_cz#96]

**Comment by boikoden** [comment]
After discussion with @hunaczech  and @cermakpavel we had decided to use **Github Actions**  for CI/CD. 

**What have done:** 
- I have tested on my [fork](https://github.com/boikoden/sousedskapomoc_cz) two actions:

1.  [PHP Composer](https://github.com/boikoden/sousedskapomoc_cz/actions/runs/60386429/workflow)
2. [PHP Lint](https://github.com/boikoden/sousedskapomoc_cz/actions/runs/60386431/workflow)


What i have found, that a lot [github actions](https://github.com/marketplace?type=actions&query=PHP)  have not a lot of stars, but one of them (PHP Setup)[https://github.com/marketplace/actions/setup-php-action] have a lot of stars and a lot of functionality, but for this setup i will need more time and some help with PHP. 

**What I Plan to do ** 
- [ ] Add directory for github actions to master branch 
- [ ] Add PHP Composer and PHP lint actions. 

Also we need to add some tests for run with github actions.
